# SSL Bot Configuration for RLBot
# This bot uses a trained SSL-level policy for Rocket League

[Bot]
name = "SSLBot"
looks_config = "appearance.cfg"
# Path to the Python file that contains your bot's code
# This path is relative to the directory that contains this config file
agent_module = "src.rlbot_integration.bot"
# The name of the class that is your bot
agent_class = "SSLBot"
# The path to the Python executable that RLBot will use to run your bot
# This can be an absolute path or a path relative to the RLBot executable
python_file = "env/Scripts/python.exe"  # Windows
# python_file = "env/bin/python"  # Linux/macOS

[Details]
developer = "SSL Bot Team"
description = "An SSL-ready Rocket League bot trained with RLGym, RocketSim, and PPO. Features curriculum learning from Bronze to SSL with advanced mechanics like aerial interceptions, wall reads, backboard plays, double taps, and flip resets."
fun_fact = "Uses a rank-based curriculum and advanced scenario sampling for SSL-level training."
github = "https://github.com/ZeroII99II/RankedSSLRLBOT"
language = "Python"
tags = ["machine learning", "reinforcement learning", "ssl", "rlgym", "rocketsim", "pytorch", "curriculum learning"]

[Bot Loadout]
# Bot appearance configuration
team_color_id = 60
custom_color_id = 0
car_id = 23  # Octane
decal_id = 0
wheels_id = 1565  # Cristiano
boost_id = 35  # Standard
antenna_id = 0
hat_id = 0
paint_finish_id = 388
custom_finish_id = 388
engine_audio_id = 0
trails_id = 3220
goal_explosion_id = 3018

[Bot Behavior]
# Bot behavior settings
use_quick_chat = true
use_team_quick_chat = true
use_auto_handbrake = false
use_auto_flip = false
use_auto_boost = false

[Bot Performance]
# Performance settings
tick_rate = 120
max_tick_rate = 240
use_flatbuffer = true
use_legacy_rendering = false

[Bot Training]
# Training-related settings (for development)
model_path = "models/exported/ssl_policy.ts"
observation_type = "ssl_obs"
action_type = "continuous_discrete"
normalize_observations = true
clip_actions = true

[Bot Safety]
# Safety and usage warnings
local_only = true
private_matches_only = true
never_use_online = true
warning_message = "This bot is for local/private matches only. Never use automated bots in online matchmaking."

