phases:
  bronze:
    description: Entry phase focusing on basic skills
    reward_weights:
      ball_to_goal: 1.0
      touch_quality: 0.2
      recovery: 0.2
      boost_economy: 0.1
    scenario_weights:
      kickoff: 0.20
      mid: 0.70
      aerial: 0.05
      wall: 0.05
    opponent_mix:
      self_play: 0.7
      scripted: 0.3
    progression_gates:
      min_games: 200
      on_target_pct: 0.30
      recoveries_per_min: 15
    min_training_steps: 10000
    max_training_steps: 20000
    eval_metrics:
      win_rate: 0.5

  gold:
    description: Intermediate phase introducing positioning and aerials
    reward_weights:
      ball_to_goal: 1.0
      touch_quality: 0.4
      recovery: 0.2
      boost_economy: 0.2
      shadowing: 0.2
    scenario_weights:
      kickoff: 0.15
      mid: 0.55
      aerial: 0.15
      wall: 0.15
    opponent_mix:
      self_play: 0.6
      scripted: 0.4
    progression_gates:
      min_games: 300
      on_target_pct: 0.45
      save_rate: 0.15
    min_training_steps: 20000
    max_training_steps: 40000
    eval_metrics:
      win_rate: 0.6

