# Curriculum Configuration for SSL Bot Training
# Defines progression from Bronze to SSL with phase-specific settings

phases:
  bronze:
    description: "Basic movement, touches, recoveries"
    reward_weights:
      ball_to_goal_velocity: 0.3
      touch_quality: 0.5
      recovery: 1.0
      boost_economy: 0.5
      aerial_intercept: 0.1
      backboard_read: 0.1
      double_tap_setup: 0.1
      flip_reset: 0.1
      fast_aerial: 0.1
    scenario_weights:
      kickoff: 0.3
      ground_play: 0.4
      simple_aerial: 0.1
      defensive_clear: 0.1
      boost_collection: 0.1
    opponent_mix:
      self_play: 0.8
      scripted_basic: 0.2
    progression_gates:
      min_win_rate: 0.6
      min_goal_rate: 0.3
      min_touch_rate: 0.4
    min_training_steps: 100000
    max_training_steps: 500000
    eval_metrics:
      win_rate: 0.6
      goal_rate: 0.3
      touch_rate: 0.4
      recovery_time: 2.0

  silver:
    description: "Improved movement, basic aerials, wall bounces"
    reward_weights:
      ball_to_goal_velocity: 0.5
      touch_quality: 0.7
      recovery: 1.0
      boost_economy: 0.7
      aerial_intercept: 0.2
      backboard_read: 0.2
      double_tap_setup: 0.1
      flip_reset: 0.1
      fast_aerial: 0.2
    scenario_weights:
      kickoff: 0.25
      ground_play: 0.3
      simple_aerial: 0.2
      wall_bounce: 0.1
      defensive_clear: 0.1
      boost_collection: 0.05
    opponent_mix:
      self_play: 0.7
      scripted_basic: 0.2
      scripted_intermediate: 0.1
    progression_gates:
      min_win_rate: 0.65
      min_goal_rate: 0.35
      min_aerial_success: 0.2
    min_training_steps: 200000
    max_training_steps: 800000
    eval_metrics:
      win_rate: 0.65
      goal_rate: 0.35
      aerial_success: 0.2
      wall_read_success: 0.1

  gold:
    description: "Boost management, positioning, wall reads"
    reward_weights:
      ball_to_goal_velocity: 0.7
      touch_quality: 1.0
      recovery: 1.0
      boost_economy: 1.0
      aerial_intercept: 0.4
      backboard_read: 0.3
      double_tap_setup: 0.2
      flip_reset: 0.1
      fast_aerial: 0.4
    scenario_weights:
      kickoff: 0.2
      ground_play: 0.25
      simple_aerial: 0.2
      wall_bounce: 0.15
      backboard_clear: 0.1
      defensive_clear: 0.05
      boost_collection: 0.05
    opponent_mix:
      self_play: 0.6
      scripted_basic: 0.2
      scripted_intermediate: 0.2
    progression_gates:
      min_win_rate: 0.7
      min_goal_rate: 0.4
      min_boost_efficiency: 0.6
    min_training_steps: 300000
    max_training_steps: 1000000
    eval_metrics:
      win_rate: 0.7
      goal_rate: 0.4
      boost_efficiency: 0.6
      wall_read_success: 0.2

  platinum:
    description: "Advanced positioning, backboard plays"
    reward_weights:
      ball_to_goal_velocity: 0.8
      touch_quality: 1.0
      recovery: 1.0
      boost_economy: 1.0
      aerial_intercept: 0.6
      backboard_read: 0.5
      double_tap_setup: 0.3
      flip_reset: 0.2
      fast_aerial: 0.6
    scenario_weights:
      kickoff: 0.15
      ground_play: 0.2
      simple_aerial: 0.2
      wall_bounce: 0.15
      backboard_clear: 0.15
      aerial_intercept: 0.1
      defensive_clear: 0.05
    opponent_mix:
      self_play: 0.5
      scripted_intermediate: 0.3
      scripted_advanced: 0.2
    progression_gates:
      min_win_rate: 0.75
      min_goal_rate: 0.45
      min_backboard_success: 0.3
    min_training_steps: 400000
    max_training_steps: 1200000
    eval_metrics:
      win_rate: 0.75
      goal_rate: 0.45
      backboard_success: 0.3
      aerial_intercept_success: 0.25

  diamond:
    description: "Power shots, dribbles, advanced aerials"
    reward_weights:
      ball_to_goal_velocity: 1.0
      touch_quality: 1.0
      recovery: 1.0
      boost_economy: 1.0
      aerial_intercept: 0.8
      backboard_read: 0.7
      double_tap_setup: 0.5
      flip_reset: 0.3
      fast_aerial: 0.8
    scenario_weights:
      kickoff: 0.1
      ground_play: 0.15
      simple_aerial: 0.15
      wall_bounce: 0.15
      backboard_clear: 0.15
      aerial_intercept: 0.15
      double_tap_setup: 0.1
      defensive_clear: 0.05
    opponent_mix:
      self_play: 0.4
      scripted_intermediate: 0.3
      scripted_advanced: 0.3
    progression_gates:
      min_win_rate: 0.8
      min_goal_rate: 0.5
      min_double_tap_success: 0.2
    min_training_steps: 500000
    max_training_steps: 1500000
    eval_metrics:
      win_rate: 0.8
      goal_rate: 0.5
      double_tap_success: 0.2
      power_shot_success: 0.3

  champion:
    description: "Advanced aerials, flip resets, complex plays"
    reward_weights:
      ball_to_goal_velocity: 1.0
      touch_quality: 1.0
      recovery: 1.0
      boost_economy: 1.0
      aerial_intercept: 1.0
      backboard_read: 0.9
      double_tap_setup: 0.7
      flip_reset: 0.5
      fast_aerial: 1.0
    scenario_weights:
      kickoff: 0.08
      ground_play: 0.12
      simple_aerial: 0.12
      wall_bounce: 0.15
      backboard_clear: 0.15
      aerial_intercept: 0.15
      double_tap_setup: 0.15
      flip_reset_setup: 0.08
    opponent_mix:
      self_play: 0.3
      scripted_advanced: 0.4
      scripted_expert: 0.3
    progression_gates:
      min_win_rate: 0.85
      min_goal_rate: 0.55
      min_flip_reset_success: 0.1
    min_training_steps: 600000
    max_training_steps: 1800000
    eval_metrics:
      win_rate: 0.85
      goal_rate: 0.55
      flip_reset_success: 0.1
      complex_aerial_success: 0.2

  gc:
    description: "Expert aerial mechanics, ceiling plays"
    reward_weights:
      ball_to_goal_velocity: 1.0
      touch_quality: 1.0
      recovery: 1.0
      boost_economy: 1.0
      aerial_intercept: 1.0
      backboard_read: 1.0
      double_tap_setup: 0.9
      flip_reset: 0.7
      fast_aerial: 1.0
    scenario_weights:
      kickoff: 0.05
      ground_play: 0.1
      simple_aerial: 0.1
      wall_bounce: 0.15
      backboard_clear: 0.15
      aerial_intercept: 0.15
      double_tap_setup: 0.15
      flip_reset_setup: 0.1
      ceiling_pinch: 0.05
    opponent_mix:
      self_play: 0.2
      scripted_advanced: 0.3
      scripted_expert: 0.5
    progression_gates:
      min_win_rate: 0.9
      min_goal_rate: 0.6
      min_ceiling_success: 0.15
    min_training_steps: 700000
    max_training_steps: 2000000
    eval_metrics:
      win_rate: 0.9
      goal_rate: 0.6
      ceiling_success: 0.15
      expert_aerial_success: 0.25

  ssl:
    description: "SSL-level mechanics, all advanced plays"
    reward_weights:
      ball_to_goal_velocity: 1.0
      touch_quality: 1.0
      recovery: 1.0
      boost_economy: 1.0
      aerial_intercept: 1.0
      backboard_read: 1.0
      double_tap_setup: 1.0
      flip_reset: 1.0
      fast_aerial: 1.0
    scenario_weights:
      kickoff: 0.05
      ground_play: 0.08
      simple_aerial: 0.08
      wall_bounce: 0.12
      backboard_clear: 0.15
      aerial_intercept: 0.15
      double_tap_setup: 0.15
      flip_reset_setup: 0.12
      ceiling_pinch: 0.1
    opponent_mix:
      self_play: 0.1
      scripted_expert: 0.9
    progression_gates:
      min_win_rate: 0.95
      min_goal_rate: 0.65
      min_ssl_mechanics: 0.3
    min_training_steps: 800000
    max_training_steps: 2500000
    eval_metrics:
      win_rate: 0.95
      goal_rate: 0.65
      ssl_mechanics_success: 0.3
      overall_skill: 0.9
