seed: 42
envs: 16
steps_per_update: 32768
minibatches: 8
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
vf_coef: 0.5
ent_coef: 0.01
lr: 3.0e-4
lr_schedule: cosine
max_grad_norm: 0.5
normalize_observations: true
normalize_rewards: true
checkpoint_every_updates: 20
eval_every_updates: 10
snapshot_pool_size: 5
action_space:
  continuous: [steer, throttle, pitch, yaw, roll]
  discrete: [jump, boost, handbrake]