"""
Training configuration consumed by ``src/training/train.py``.

The file groups related settings into logical blocks:

* ``policy``   – model architecture options.
* ``ppo``      – optimisation hyperparameters.
* ``training`` – runtime behaviour like evaluation and checkpointing.
* ``env``      – environment parameters such as team size.
* ``device``   – hardware selection.
* ``curriculum`` – progression settings shared with the trainer.
"""

policy:
  obs_dim: 107
  hidden_sizes: [1024, 1024, 512]
  continuous_actions: 5
  discrete_actions: 3
  use_attention: true
  num_heads: 8
  head_dim: 64
  dropout: 0.1
  activation: silu

ppo:
  steps_per_update: 32768
  mini_batches: 8
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  actor_lr: 3.0e-4
  critic_lr: 3.0e-4
  value_loss_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 0.5

training:
  seed: 42
  eval_frequency: 327680
  eval_episodes: 10
  save_frequency: 655360

env:
  team_size: 3
  tick_skip: 8
  self_play: true
  use_injector: true
  spawn_opponents: false

device:
  auto_detect: true
  cuda: true
  device: cpu

curriculum:
  auto_progress: true
  progress_check_frequency: 200000

